import { NextRequest, NextResponse } from 'next/server';

// Force dynamic rendering
export const dynamic = 'force-dynamic';

export async function POST(request: NextRequest) {
  try {
    const data = await request.json();

    // Generate CSV content
    const csvContent = [
      'Condition,Probability (%)',
      `Very Hot,${data.hot}`,
      `Very Cold,${data.cold}`,
      `Very Windy,${data.windy}`,
      `Very Wet,${data.wet}`,
      `Very Uncomfortable,${data.uncomfortable}`,
      '',
      'Metadata',
      `Location,"${data.location.address || `${data.location.lat}, ${data.location.lng}`}"`,
      `Date,"${data.date}"`,
      `Activity,"${data.activity}"`,
      '',
      'Generated by NASA Weather Planner',
      `Export Date,"${new Date().toISOString()}"`,
    ].join('\n');

    const response = new NextResponse(csvContent);
    response.headers.set('Content-Type', 'text/csv');
    response.headers.set('Content-Disposition', `attachment; filename="weather-report-${new Date().toISOString().split('T')[0]}.csv"`);

    return response;
  } catch (error) {
    console.error('Export API error:', error);
    return NextResponse.json({ error: 'Failed to export data' }, { status: 500 });
  }
}